---

# Linux x64 compilation
kind: pipeline
name: linux_x64

steps:
  - name: build
    image: rikorose/gcc-cmake:gcc-8
    commands:
    - apt-get install libboost-all-dev
    - gcc --version
    - cmake -version
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cd src
    - strip TurtleGold* zedwallet* miner cryptotest wallet-api
    - tar cxvf "${DRONE_REPO_NAME}_${DRONE_TAG}_${DRONE_RUNNER_PLATFORM}_gcc_8.tar.gz" TurtleGold* zedwallet* miner cryptotest wallet-api

  - name: github_release
    image: plugins/github-release
    settings:
      files: *_gcc_8.tar.gz
    when: tag
